name: Build and publish to PyPI

on:
  push:
    branches: [ main ]   # publishes to TestPyPI
  release:
    types: [ published ] # publishes to PyPI when a GitHub Release is published
  workflow_dispatch:

jobs:
  publish-pypi:
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/slicr/
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install --upgrade pip build
      - run: python -m build
      - name: Publish to PyPI (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
